name: Алексей Плеханов · Блог

encoding: UTF-8
excerpt_separator: "<!-- more -->"
future: false
markdown: kramdown
permalink: :year/:month/:title/
paginate: 5
paginate_path: page:num
pygments: true
timezone: Europe/Kiev