name: Алексей Плеханов · Блог

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        :year/:month/:title/

# Setup
title:            Алексей Плеханов
tagline:          Блог
description:      Просто крутой блог
url:              http://gh.asft.org
encoding: UTF-8

paginate:         5

timezone:         Europe/Kiev

social:
    github:  https://github.com/alexsoft
    twitter: https://twitter.com/alex_soft
theme: jekyll-theme-hacker